### ISSUE TITLE
add_capsule forces PERSIST_ACROSS_RESET and INITIATE_RESET flags

### ISSUE THREAD

**Issue by semihalf-szczepanek-bartosz** [vathpela/fwup#74]
Hi,

according to UEFI specification, CAPSULE_FLAGS_PERSIST_ACROSS_RESET and CAPSULE_FLAGS_INITIATE_RESET flags are optional ([spec](http://www.uefi.org/sites/default/files/resources/UEFI%20Spec%202_6.pdf) page 1097), but fwupdate forces these before passing capsules to UpdateCapsule ([1](https://github.com/rhboot/fwupdate/blob/master/efi/fwupdate.c#L714), [2](https://github.com/rhboot/fwupdate/blob/master/efi/fwupdate.c#L733)). What is the reasoning behind that? Commit message doesn't help.

Thanks,
Bartosz

**Comment by vathpela** [comment]
So, the problem here is that there's no good way to discover what fwupdate should set.  Additionally, on x86 machines we've had the goal to be 100% compatible with Microsoft's behavior, because we know Windows logo certification rules determine that's all that will ever really be tested by most hardware vendors.  In https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/processing-updates  they say:

> The Windows OS loader creates capsule headers using the information from each update’s corresponding ESRT entry, which describes the GUID and flags to use when calling UEFI UpdateCapsule. In setting each capsule header’s flags field, the Windows OS loader always sets CAPSULE_FLAGS_PERSIST_ACROSS_RESET and CAPSULE_FLAGS_INITIATE_RESET. The Windows OS loader may additionally set CAPSULE_FLAGS_POPULATE_SYSTEM_TABLE for firmware types DEVICE_FIRMWARE, if the capsule flag was specified in the INF for the driver package. Proprietary capsule flags may also be specified in the INF and when specified will additionally be included when calling UEFI UpdateCapsule

So we also always set those two flags (though I haven't properly plumbed through the ability to get flags from the .inf as well, yet.)

**Comment by superm1** [comment]
Plumbing through the stuff to get that information from the INF is no joke either.  It would mean changing things across 3 projects.
* appstream-glib needs to parse it, 
* fwupd needs to store it in the database, and 
* pass it to libfwup/fwupdate somehow when flashing it.

**Comment by hughsie** [comment]
So what exact data needs to be propagated? I'd much rather have metadata NeedsSystemTable=true in the XML file (and some guidance on when to set it...), but this obviously needs to be extendable in the future.

**Comment by superm1** [comment]
Since Windows is always setting those flags and this project is aiming for compatibility with Windows capsules I'm closing this issue.  If later we discover a reason that they shouldn't always be set we can revisit this.
